const mongoose = require('mongoose');

/**
 * Schema for storing a user's critical medical information.
 * The _id generated by MongoDB will act as the unique URL token (Zero-Auth).
 */
const medicalProfileSchema = new mongoose.Schema(
  {
    fullName: {
      type: String,
      required: [true, 'Full name is required'],
      trim: true,
      maxLength: [100, 'Name cannot exceed 100 characters']
    },
    bloodGroup: {
      type: String,
      required: [true, 'Blood group is required'],
      enum: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', 'Unknown']
    },
    allergies: {
      type: String,
      default: 'None reported',
      trim: true
    },
    medicalConditions: {
      type: String,
      default: 'None reported',
      trim: true
    },
    emergencyContactEmail: {
      type: String,
      required: [true, 'Emergency contact email is required'],
      trim: true,
      lowercase: true,
      // Basic regex for email validation
      match: [
        /^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/,
        'Please provide a valid email address'
      ]
    },
    isActive: {
      type: Boolean,
      default: true // Allows for soft deletion in the future
    }
  },
  {
    // Automatically adds createdAt and updatedAt timestamp fields
    timestamps: true 
  }
);

module.exports = mongoose.model('MedicalProfile', medicalProfileSchema);